language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

cache:
  directories:
    - node_modules
    - ~/.nvm

before_install:
  - export NVM_DIR=~/.nvm
  - which nvm || curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | bash
  - source ~/.nvm/nvm.sh --install
  - nvm install 5
  - npm install

before_script:
  - npm start &
  - npm run appium &
  - sleep 10
  - npm run build-ios

script:
  - npm test

