language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator9.3

cache:
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install

before_script:
  - npm run flow-start
  - ln -sf .env.local .env
  - npm run build-ios
  - npm run appium &
  - sleep 10

script:
  - npm run flow
  - npm run lint
  - npm run jest
  - npm run integration

